/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.Controller;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.Autor;
import model.Knjiga;
import model.Zanr;

/**
 *
 * @author vlada
 */
public class Dodavanje extends javax.swing.JDialog {

    /**
     * Creates new form Dodavanje
     */
    
    
    private Controller controller;
    private Knjiga knjigaZaIzmenu;
    private GlavnaForma gf;
    
    public Dodavanje(java.awt.Frame parent, boolean modal, Knjiga knjigazaizmenu) {
        super(parent, modal);
        initComponents();
        controller = Controller.getInstance();
        this.gf = (GlavnaForma) parent;
        popuniComboBoxAutorima();
        if (knjigazaizmenu != null) {
            this.knjigaZaIzmenu = knjigazaizmenu;

            jTextFieldNaziv.setText(knjigaZaIzmenu.getNaslov());
            jComboBoxAutori.setSelectedItem(knjigaZaIzmenu.getAutor());
            jTextFieldISBN.setText(knjigaZaIzmenu.getISBN());
            jTextFieldISBN.setEnabled(false);
            jTextFieldGodIzdanja.setText(String.valueOf(knjigaZaIzmenu.getGodinaIzdanja()));

            jButton_dodaj.setVisible(false);
        } else {
            jButton_izmeni.setVisible(false);
        }
    }

    Dodavanje(GlavnaForma aThis, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    
    
    
    
    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldNaziv = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldISBN = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxAutori = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldGodIzdanja = new javax.swing.JTextField();
        jButton_dodaj = new javax.swing.JButton();
        jButton_odustani = new javax.swing.JButton();
        jButton_izmeni = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jComboBox_Zanr = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Naziv");

        jLabel2.setText("ISBN");

        jLabel3.setText("Autor");

        jComboBoxAutori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAutoriActionPerformed(evt);
            }
        });

        jLabel4.setText("Godina");

        jTextFieldGodIzdanja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGodIzdanjaActionPerformed(evt);
            }
        });

        jButton_dodaj.setText("Dodaj");
        jButton_dodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_dodajActionPerformed(evt);
            }
        });

        jButton_odustani.setText("Odustani");

        jButton_izmeni.setText("Izmeni");
        jButton_izmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_izmeniActionPerformed(evt);
            }
        });

        jLabel5.setText("Zanr");

        jComboBox_Zanr.setModel(new DefaultComboBoxModel(Zanr.values()));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldISBN)
                                    .addComponent(jTextFieldNaziv)
                                    .addComponent(jComboBoxAutori, 0, 231, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldGodIzdanja, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                                    .addComponent(jComboBox_Zanr, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_dodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jButton_izmeni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(jButton_odustani)
                        .addGap(38, 38, 38))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxAutori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldGodIzdanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox_Zanr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_dodaj)
                    .addComponent(jButton_izmeni)
                    .addComponent(jButton_odustani))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxAutoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAutoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxAutoriActionPerformed

    private void jTextFieldGodIzdanjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGodIzdanjaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGodIzdanjaActionPerformed

    private void jButton_izmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_izmeniActionPerformed
           String naziv = jTextFieldNaziv.getText();
           String isbn = jTextFieldISBN.getText();
           int godIzdanja;

           try {
               godIzdanja = Integer.parseInt(jTextFieldGodIzdanja.getText());
           } catch (NumberFormatException e) {
               JOptionPane.showMessageDialog(this, "Godina izdanja mora biti broj!", "Greška", JOptionPane.ERROR_MESSAGE);
               return;
           }
           Zanr zanr = (Zanr)jComboBox_Zanr.getSelectedItem();
           Autor odabraniAutor = (Autor) jComboBoxAutori.getSelectedItem();
           
            knjigaZaIzmenu.setAutor(odabraniAutor);
            knjigaZaIzmenu.setNaslov(naziv);
            knjigaZaIzmenu.setGodinaIzdanja(godIzdanja);
            knjigaZaIzmenu.setZanr(zanr);

           gf.osveziTabelu();
           JOptionPane.showMessageDialog(this, "Knjiga je uspesno dodata", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
           this.dispose();
    }//GEN-LAST:event_jButton_izmeniActionPerformed

    private void jButton_dodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_dodajActionPerformed
        int godIzdanja;
        String naziv = jTextFieldNaziv.getText();
        String isbn = jTextFieldISBN.getText();
        try{
        godIzdanja = Integer.parseInt(jTextFieldGodIzdanja.getText());
        
     } catch (NumberFormatException e){
         JOptionPane.showMessageDialog(this, "Niste uneli ispravno podatke", "Greska", JOptionPane.WARNING_MESSAGE);
        return;
    }//GEN-LAST:event_jButton_dodajActionPerformed
    Zanr zanr = (Zanr) jComboBox_Zanr.getSelectedItem();
    Autor odabraniAutor = (Autor) jComboBoxAutori.getSelectedItem();
    Knjiga knjiga = new Knjiga(naziv, odabraniAutor, isbn, godIzdanja, zanr);
    controller.dodajKnjigu(knjiga);
    gf.osveziTabelu();
    JOptionPane.showMessageDialog(this, "Knjiga je uspesno dodata", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
    this.dispose();
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dodavanje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dodavanje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dodavanje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dodavanje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Dodavanje dialog = new Dodavanje((GlavnaForma) new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_dodaj;
    private javax.swing.JButton jButton_izmeni;
    private javax.swing.JButton jButton_odustani;
    private javax.swing.JComboBox<Autor> jComboBoxAutori;
    private javax.swing.JComboBox<String> jComboBox_Zanr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextFieldGodIzdanja;
    private javax.swing.JTextField jTextFieldISBN;
    private javax.swing.JTextField jTextFieldNaziv;
    // End of variables declaration//GEN-END:variables

    private void popuniComboBoxAutorima() {
        jComboBoxAutori.removeAllItems();
        List<Autor> autori = controller.getListaAutora();
        for(Autor autor : autori){
            jComboBoxAutori.addItem(autor);
    }
}
}